apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mar13-2
  janus-idp.io/tekton: mar13-2
  backstage.io/kubernetes-id: mar13-2
  backstage.io/kubernetes-namespace: mar13-2 
  app.kubernetes.io/part-of: mar13-2
resources: 
- deployment.yaml
- route.yaml
- service.yaml
